/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/kailash_sprit.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/kailash_sprit.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_node.geometry} material={materials.material} />
    </group>
  )
}

useGLTF.preload('/kailash_sprit.glb')
