import { MathFunction, MathVariable, COLORS } from "./mathTypes";

export const MATH_EXAMPLES: Record<string, { functions: MathFunction[]; variables: MathVariable[] }> = {
  Lissajous: {
    functions: [
      {
        id: "f1",
        expr: "[A * sin(a*t + d + time), B * sin(b*t)]",
        type: "parametric",
        color: COLORS[0],
        visible: true,
      },
    ],
    variables: [
      {
        id: "v1",
        name: "A",
        displayName: "Amplitude X",
        description: "",
        value: 3,
        defaultValue: 3,
        min: 0,
        max: 5,
        step: 0.1,
        groupId: "default",
      },
      {
        id: "v2",
        name: "B",
        displayName: "Amplitude Y",
        description: "",
        value: 3,
        defaultValue: 3,
        min: 0,
        max: 5,
        step: 0.1,
        groupId: "default",
      },
      {
        id: "v3",
        name: "a",
        displayName: "Freq X",
        description: "",
        value: 3,
        defaultValue: 3,
        min: 0,
        max: 5,
        step: 0.1,
        groupId: "default",
      },
      {
        id: "v4",
        name: "b",
        displayName: "Freq Y",
        description: "",
        value: 4,
        defaultValue: 4,
        min: 0,
        max: 5,
        step: 0.1,
        groupId: "default",
      },
      {
        id: "v5",
        name: "d",
        displayName: "Phase",
        description: "",
        value: Math.PI / 2,
        defaultValue: Math.PI / 2,
        min: 0,
        max: Math.PI * 2,
        step: 0.1,
        groupId: "default",
      },
    ],
  },
  Fourier: {
    functions: [
      {
        id: "f1",
        expr: "4/pi * (sin(x) + sin(3*x)/3 + sin(5*x)/5 + sin(7*x)/7)",
        type: "function",
        color: COLORS[2],
        visible: true,
      },
    ],
    variables: [],
  },
  Wave: {
    functions: [
      {
        id: "f1",
        expr: "A * sin(k*x - w*t + phi)",
        type: "function",
        color: COLORS[3],
        visible: true,
      },
    ],
    variables: [
      {
        id: "v1",
        name: "A",
        displayName: "Amplitude",
        description: "",
        value: 2,
        defaultValue: 2,
        min: 0,
        max: 5,
        step: 0.1,
        groupId: "default",
      },
      {
        id: "v2",
        name: "k",
        displayName: "Wave Number",
        description: "",
        value: 2,
        defaultValue: 2,
        min: 0,
        max: 10,
        step: 0.1,
        groupId: "default",
      },
      {
        id: "v3",
        name: "w",
        displayName: "Angular Freq",
        description: "",
        value: 3,
        defaultValue: 3,
        min: 0,
        max: 10,
        step: 0.1,
        groupId: "default",
      },
      {
        id: "v4",
        name: "phi",
        displayName: "Phase String",
        description: "",
        value: 0,
        defaultValue: 0,
        min: 0,
        max: 6.28,
        step: 0.1,
        groupId: "default",
      },
    ],
  },
  Geometry: {
    functions: [
      {
        id: "f1",
        expr: "A = [2, 3]",
        type: "point",
        color: COLORS[0],
        visible: true,
      },
      {
        id: "f2",
        expr: "B = [-1, 2]",
        type: "point",
        color: COLORS[1],
        visible: true,
      },
      {
        id: "f3",
        expr: "C = [1, -2]",
        type: "point",
        color: COLORS[2],
        visible: true,
      },
      {
        id: "f4",
        expr: "[A, B, C]",
        type: "polygon",
        color: COLORS[3],
        visible: true,
      },
      {
        id: "f5",
        expr: "v = A - B",
        type: "vector",
        color: COLORS[4],
        visible: true,
      },
      {
        id: "f6",
        expr: "[r * cos(t), r * sin(t)]",
        type: "parametric",
        color: COLORS[5],
        visible: true,
      },
    ],
    variables: [
      {
        id: "v1",
        name: "r",
        displayName: "Circle Radius",
        description: "Radius of implicit circle",
        value: 2,
        defaultValue: 2,
        min: 0.1,
        max: 10,
        step: 0.1,
        groupId: "default",
      },
    ],
  },
  Statistics: {
    functions: [
      {
        id: "f1",
        expr: "(1/(sigma * sqrt(2*pi))) * e^(-0.5 * ((x - mu)/sigma)^2)",
        type: "function",
        color: COLORS[4],
        visible: true,
      },
    ],
    variables: [
      {
        id: "v1",
        name: "mu",
        displayName: "Mean",
        description: "Center of distribution",
        value: 0,
        defaultValue: 0,
        min: -10,
        max: 10,
        step: 0.5,
        groupId: "default",
      },
      {
        id: "v2",
        name: "sigma",
        displayName: "Standard Dev",
        description: "Spread of distribution",
        value: 1,
        defaultValue: 1,
        min: 0.1,
        max: 5,
        step: 0.1,
        groupId: "default",
      },
    ],
  },
  Matrix: {
    functions: [
      {
        id: "f1",
        expr: "A = [2, 3]",
        type: "point",
        color: COLORS[0],
        visible: true,
        isDraggable: true,
      },
      {
        id: "f2",
        expr: "B = [-2, -1]",
        type: "point",
        color: COLORS[1],
        visible: true,
        isDraggable: true,
      },
      {
        id: "f3",
        expr: "[[x, y, 1], [A[1], A[2], 1], [B[1], B[2], 1]] = 0",
        type: "implicit",
        color: COLORS[2],
        visible: true,
      },
    ],
    variables: [],
  },
};
