/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core';
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { NetworkFirst, CacheFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { db } from './lib/db';

declare let self: ServiceWorkerGlobalScope;

clientsClaim();

// Cleanup outdated caches automatically
cleanupOutdatedCaches();

// Precache Vite assets generated by build
precacheAndRoute(self.__WB_MANIFEST || []);

// State for Pyodide synchronous STDIN bridge
const pendingRequests = new Map<string, (res: Response) => void>();

// --- STDIN Custom Message Handler ---
self.addEventListener('message', (event) => {
  const data = event.data;
  if (!data) return;

  if (data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  } else if (data.type === 'STDIN_SUBMIT') {
    const { sessionId, value } = data;
    if (pendingRequests.has(sessionId)) {
      const resolve = pendingRequests.get(sessionId)!;
      pendingRequests.delete(sessionId);
      resolve(new Response(JSON.stringify({ value: value }), {
        status: 200,
        headers: { 'Content-Type': 'application/json' }
      }));
    }
  } else if (data.type === 'STDIN_CANCEL') {
    const { sessionId } = data;
    if (pendingRequests.has(sessionId)) {
      const resolve = pendingRequests.get(sessionId)!;
      pendingRequests.delete(sessionId);
      resolve(new Response(JSON.stringify({ value: null, cancelled: true }), {
        status: 200,
        headers: { 'Content-Type': 'application/json' }
      }));
    }
  }
});

// --- Intercept Fetch for STDIN and Share Target ---
self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);

  // Intercept PWA Share Target POST
  if (url.pathname === '/share-receiver/' && event.request.method === 'POST') {
    event.respondWith((async () => {
      try {
        const formData = await event.request.formData();
        const files = formData.getAll('files') as File[];
        const title = (formData.get('name') || formData.get('title')) as string;
        const text = (formData.get('description') || formData.get('text')) as string;
        const link = (formData.get('link') || formData.get('url')) as string;

        const sharedId = `share_${Date.now()}`;
        await db.sharedFiles.put({
          id: sharedId,
          files: files,
          title: title,
          text: text,
          link: link,
          timestamp: Date.now()
        });
        
        // Redirect to the main app with the shared ID
        return Response.redirect(`/?shared_id=${sharedId}`, 303);
      } catch (err) {
        console.error('[SW] Share target failed:', err);
        return Response.redirect('/', 303);
      }
    })());
    return;
  }

  // STDIN Synchronous Sync
  if (url.pathname === '/api/stdin-get') {
    const sessionId = url.searchParams.get('sessionId');
    if (sessionId) {
      event.respondWith(
        new Promise<Response>((resolve) => {
          pendingRequests.set(sessionId, resolve);
          
          // Safety timeout of 10 minutes to prevent permanent leak
          setTimeout(() => {
            if (pendingRequests.has(sessionId)) {
              pendingRequests.delete(sessionId);
              resolve(new Response(JSON.stringify({ value: null, timeout: true }), {
                status: 200,
                headers: { 'Content-Type': 'application/json' }
              }));
            }
          }, 600000);
        })
      );
    }
    return;
  }
});

// --- Workbox Routing ---

// Serve OPFS Tessdata
registerRoute(
  ({ url }) => url.pathname.startsWith('/opfs-tessdata/'),
  async ({ url }) => {
    try {
      const filename = url.pathname.split('/').pop();
      if (!filename) throw new Error('No filename');
      
      const opfsRoot = await navigator.storage.getDirectory();
      const fileHandle = await opfsRoot.getFileHandle(filename);
      const file = await fileHandle.getFile();
      
      return new Response(file, {
        headers: {
          'Content-Type': 'application/x-gzip',
          'Cache-Control': 'public, max-age=31536000'
        }
      });
    } catch (e) {
      console.warn('[SW] File not found in OPFS:', url.pathname);
      return new Response('Not found in OPFS', { status: 404 });
    }
  }
);

registerRoute(
  ({ url }) => url.pathname.startsWith('/api/') && url.pathname !== '/api/stdin-get',
  new NetworkFirst({
    cacheName: 'api-cache',
    networkTimeoutSeconds: 5,
  })
);

// Cache images with an expiration plugin
registerRoute(
  ({ request, url }) => request.destination === 'image' || url.pathname.match(/\.(png|jpg|jpeg|gif|webp|svg)$/i),
  new CacheFirst({
    cacheName: 'images-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
      }),
    ],
  })
);

// Cache CSS and JS chunks using CacheFirst as Vite adds content hashes
registerRoute(
  ({ request, url }) => request.destination === 'style' || request.destination === 'script' || url.pathname.includes('/assets/'),
  new CacheFirst({
    cacheName: 'assets-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 200,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
      }),
    ],
  })
);

// Cache fonts
registerRoute(
  ({ request }) => request.destination === 'font',
  new StaleWhileRevalidate({
    cacheName: 'fonts-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 20,
        maxAgeSeconds: 60 * 24 * 60 * 60, // 60 Days
      }),
    ],
  })
);

// SPA Navigation Fallback
// Navigations will go to the network first to ensure we get the latest HTML
registerRoute(
  new NavigationRoute(
    new NetworkFirst({
      cacheName: 'html-cache',
      networkTimeoutSeconds: 3,
    })
  )
);
