/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core';
import { precacheAndRoute, cleanupOutdatedCaches, matchPrecache } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { NetworkFirst, CacheFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { db } from './lib/db';

declare let self: ServiceWorkerGlobalScope;

clientsClaim();

// Cleanup outdated caches automatically
cleanupOutdatedCaches();

// Precache Vite assets generated by build
precacheAndRoute(self.__WB_MANIFEST || []);

// State for Pyodide synchronous STDIN bridge
const pendingRequests = new Map<string, (res: Response) => void>();

// --- STDIN Custom Message Handler ---
self.addEventListener('message', (event) => {
  const data = event.data;
  if (!data) return;

  if (data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  } else if (data.type === 'STDIN_SUBMIT') {
    const { sessionId, value } = data;
    if (pendingRequests.has(sessionId)) {
      const resolve = pendingRequests.get(sessionId)!;
      pendingRequests.delete(sessionId);
      resolve(new Response(JSON.stringify({ value: value }), {
        status: 200,
        headers: { 'Content-Type': 'application/json' }
      }));
    }
  } else if (data.type === 'STDIN_CANCEL') {
    const { sessionId } = data;
    if (pendingRequests.has(sessionId)) {
      const resolve = pendingRequests.get(sessionId)!;
      pendingRequests.delete(sessionId);
      resolve(new Response(JSON.stringify({ value: null, cancelled: true }), {
        status: 200,
        headers: { 'Content-Type': 'application/json' }
      }));
    }
  }
});

// --- Intercept Fetch for STDIN and Share Target ---
self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);

  if ((url.pathname === '/share-receiver/' || url.pathname === '/share-receiver') && event.request.method === 'POST') {
    event.respondWith((async () => {
      try {
        const formData = await event.request.formData();
        const files = formData.getAll('files') as File[];
        const title = (formData.get('name') || formData.get('title')) as string;
        const text = (formData.get('description') || formData.get('text')) as string;
        const link = (formData.get('link') || formData.get('url')) as string;

        const sharedId = `share_${Date.now()}`;
        await db.sharedFiles.put({
          id: sharedId,
          files: files,
          title: title,
          text: text,
          link: link,
          timestamp: Date.now()
        });
        
        // Use HTML meta refresh to redirect reliably across all browsers for POST Share Targets
        const redirectUrl = `/?shared_id=${sharedId}`;
        const html = `<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0;url=${redirectUrl}"></head><body>Redirecting...</body></html>`;
        
        return new Response(html, {
          status: 200,
          headers: { 'Content-Type': 'text/html' }
        });
      } catch (err) {
        console.error('[SW] Share target failed:', err);
        const html = `<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0;url=/"></head><body>Redirecting...</body></html>`;
        return new Response(html, {
          status: 200,
          headers: { 'Content-Type': 'text/html' }
        });
      }
    })());
    return;
  }

  // STDIN Synchronous Sync
  if (url.pathname === '/api/stdin-get') {
    const sessionId = url.searchParams.get('sessionId');
    if (sessionId) {
      event.respondWith(
        new Promise<Response>((resolve) => {
          pendingRequests.set(sessionId, resolve);
          
          // Safety timeout of 10 minutes to prevent permanent leak
          setTimeout(() => {
            if (pendingRequests.has(sessionId)) {
              pendingRequests.delete(sessionId);
              resolve(new Response(JSON.stringify({ value: null, timeout: true }), {
                status: 200,
                headers: { 'Content-Type': 'application/json' }
              }));
            }
          }, 600000);
        })
      );
    }
    return;
  }
});

// --- Workbox Routing ---

// Serve OPFS Tessdata
registerRoute(
  ({ url }) => url.pathname.startsWith('/opfs-tessdata/'),
  async ({ url }) => {
    try {
      const filename = url.pathname.split('/').pop();
      if (!filename) throw new Error('No filename');
      
      const opfsRoot = await navigator.storage.getDirectory();
      const fileHandle = await opfsRoot.getFileHandle(filename);
      const file = await fileHandle.getFile();
      
      return new Response(file, {
        headers: {
          'Content-Type': 'application/x-gzip',
          'Cache-Control': 'public, max-age=31536000'
        }
      });
    } catch (e) {
      console.warn('[SW] File not found in OPFS:', url.pathname);
      return new Response('Not found in OPFS', { status: 404 });
    }
  }
);

registerRoute(
  ({ url }) => url.pathname.startsWith('/api/') && url.pathname !== '/api/stdin-get',
  new NetworkFirst({
    cacheName: 'api-cache',
    networkTimeoutSeconds: 5,
  })
);

// --- Libraries loaded from CDNs at run time ---
//
// pyodide, the jsquash codecs, Google Fonts and a few others are fetched from a CDN on first use
// rather than bundled. Their URLs are pinned to a version, so the first download can be kept and
// served from then on - which is what lets them work offline afterwards. Opaque responses (a plain
// <script> or <link> without CORS) are kept too: they are all such a tag ever gets.
const CDN_HOSTS = new Set([
  'unpkg.com',
  'cdn.jsdelivr.net',
  'cdnjs.cloudflare.com',
  'fonts.googleapis.com',
  'fonts.gstatic.com',
]);

const keepOkOrOpaque = {
  cacheWillUpdate: async ({ response }: { response: Response }) =>
    response && (response.ok || response.type === 'opaque') ? response : null,
};

registerRoute(
  ({ url }) => CDN_HOSTS.has(url.hostname),
  new CacheFirst({
    cacheName: 'cdn-cache',
    plugins: [
      keepOkOrOpaque,
      new ExpirationPlugin({
        maxEntries: 400,
        maxAgeSeconds: 90 * 24 * 60 * 60, // 90 Days
        purgeOnQuotaError: true,
      }),
    ],
  })
);

// Cache images with an expiration plugin
registerRoute(
  ({ request, url }) => request.destination === 'image' || url.pathname.match(/\.(png|jpg|jpeg|gif|webp|svg)$/i),
  new CacheFirst({
    cacheName: 'images-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
      }),
    ],
  })
);

// Cache CSS and JS chunks using CacheFirst as Vite adds content hashes
registerRoute(
  ({ request, url }) => request.destination === 'style' || request.destination === 'script' || url.pathname.includes('/assets/'),
  new CacheFirst({
    cacheName: 'assets-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 200,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
      }),
    ],
  })
);

// Cache fonts
registerRoute(
  ({ request }) => request.destination === 'font',
  new StaleWhileRevalidate({
    cacheName: 'fonts-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 20,
        maxAgeSeconds: 60 * 24 * 60 * 60, // 60 Days
      }),
    ],
  })
);

// --- App shell for every navigation ---
//
// Online, the page comes from the network so a fresh deploy is picked up. When that fails -
// offline, or a connection too slow to wait for - the precached index.html is served instead.
// That is the page this worker's precache was built with, so every lazily loaded chunk it asks for
// is in the same precache.
//
// This used to go through a separate HTML cache, which broke offline in two ways: it could hand
// out a page from a newer deploy than the cached chunks (screens then failed to open), and it could
// never answer a URL it had not seen before - such as the share target's `/?shared_id=...`
// redirect, which is unique every time.
const NAVIGATION_TIMEOUT_MS = 4000;

const appShell = async (request: Request): Promise<Response> => {
  try {
    const network = await Promise.race([
      fetch(request),
      new Promise<never>((_, reject) => setTimeout(() => reject(new Error('navigation timeout')), NAVIGATION_TIMEOUT_MS)),
    ]);
    // Redirects and ordinary pages pass straight through; only a failing server falls back.
    if (network.status < 500) return network;
  } catch {
    // Offline or too slow: fall through to the app shell.
  }
  return (await matchPrecache('/index.html')) || Response.error();
};

registerRoute(new NavigationRoute(({ request }) => appShell(request), { denylist: [/^\/api\//] }));

// Navigations used to be cached here; the precached app shell replaces it.
self.addEventListener('activate', (event) => {
  event.waitUntil(caches.delete('html-cache'));
});
