/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core';
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { NetworkFirst, CacheFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

declare let self: ServiceWorkerGlobalScope;

self.skipWaiting();
clientsClaim();

// Cleanup outdated caches automatically
cleanupOutdatedCaches();

// Precache Vite assets generated by build
precacheAndRoute(self.__WB_MANIFEST || []);

// State for Pyodide synchronous STDIN bridge
const pendingRequests = new Map<string, (res: Response) => void>();

// --- STDIN Custom Message Handler ---
self.addEventListener('message', (event) => {
  const data = event.data;
  if (!data) return;

  if (data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  } else if (data.type === 'STDIN_SUBMIT') {
    const { sessionId, value } = data;
    if (pendingRequests.has(sessionId)) {
      const resolve = pendingRequests.get(sessionId)!;
      pendingRequests.delete(sessionId);
      resolve(new Response(JSON.stringify({ value: value }), {
        status: 200,
        headers: { 'Content-Type': 'application/json' }
      }));
    }
  } else if (data.type === 'STDIN_CANCEL') {
    const { sessionId } = data;
    if (pendingRequests.has(sessionId)) {
      const resolve = pendingRequests.get(sessionId)!;
      pendingRequests.delete(sessionId);
      resolve(new Response(JSON.stringify({ value: null, cancelled: true }), {
        status: 200,
        headers: { 'Content-Type': 'application/json' }
      }));
    }
  }
});

// --- Intercept Fetch for STDIN ---
self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);

  // STDIN Synchronous Sync
  if (url.pathname === '/api/stdin-get') {
    const sessionId = url.searchParams.get('sessionId');
    if (sessionId) {
      event.respondWith(
        new Promise<Response>((resolve) => {
          pendingRequests.set(sessionId, resolve);
          
          // Safety timeout of 10 minutes to prevent permanent leak
          setTimeout(() => {
            if (pendingRequests.has(sessionId)) {
              pendingRequests.delete(sessionId);
              resolve(new Response(JSON.stringify({ value: null, timeout: true }), {
                status: 200,
                headers: { 'Content-Type': 'application/json' }
              }));
            }
          }, 600000);
        })
      );
    }
    return;
  }
});

// --- Workbox Routing ---

// API Requests
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/') && url.pathname !== '/api/stdin-get',
  new NetworkFirst({
    cacheName: 'api-cache',
    networkTimeoutSeconds: 5,
  })
);

// Cache images with an expiration plugin
registerRoute(
  ({ request, url }) => request.destination === 'image' || url.pathname.match(/\.(png|jpg|jpeg|gif|webp|svg)$/i),
  new CacheFirst({
    cacheName: 'images-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
      }),
    ],
  })
);

// Cache CSS and JS chunks using CacheFirst as Vite adds content hashes
registerRoute(
  ({ request, url }) => request.destination === 'style' || request.destination === 'script' || url.pathname.includes('/assets/'),
  new CacheFirst({
    cacheName: 'assets-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 200,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
      }),
    ],
  })
);

// Cache fonts
registerRoute(
  ({ request }) => request.destination === 'font',
  new StaleWhileRevalidate({
    cacheName: 'fonts-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 20,
        maxAgeSeconds: 60 * 24 * 60 * 60, // 60 Days
      }),
    ],
  })
);

// SPA Navigation Fallback
// Navigations will go to the network first to ensure we get the latest HTML
registerRoute(
  new NavigationRoute(
    new NetworkFirst({
      cacheName: 'html-cache',
      networkTimeoutSeconds: 3,
    })
  )
);
